

const CHALLAN_FETCH_STATUS = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED',
    FAILED_FALLBACK: 'FAILED_FALLBACK',
    PENDING: 'PENDING',
    PARTIAL: 'PARTIAL',
    RECORD_NOT_FOUND:'RECORD_NOT_FOUND'
}

module.exports = {
    CHALLAN_FETCH_STATUS
}